name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        timeout-minutes: 2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
        timeout-minutes: 2

      - name: Install npm Dependencies
        run: npm install
        timeout-minutes: 2

      - name: Run Freeze Build
        run: python app/freeze.py
        timeout-minutes: 2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "app/build"
        timeout-minutes: 2

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        timeout-minutes: 2
